/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TypescriptdslRuntimeModule extends AbstractTypescriptdslRuntimeModule {
}
