/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.validation

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TypescriptdslValidator extends AbstractTypescriptdslValidator {
}
